# Configuration is done using preload, which loads an image into memory. Then, the wallpaper keyword is used to apply the preloaded image to your monitor(s)
preload = /home/me/amongus.png
wallpaper = monitor, /home/me/amongus.png
